### PR TITLE
Check ncurses path

### LINKED ISSUE #20: Unix ncurses build fails on Ubuntu 20.04
Trying to compile on Ubuntu 20.04 ends in error:

```
$ make
cc -O2 -o level9 -I.. ../level9.c unix-curses.c -lncurses
unix-curses.c:80:10: fatal error: ncurses/curses.h: El fitxer o directori no existeix
   80 | #include <ncurses/curses.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: level9] Error 1
```

### PR DESCRIPTION
**Pull request by cibersheep**
Check if the path exists for ncurses

Fixes #20

### CODE REVIEW

**Comment by DavidKinder** [comment]
I don't like this due to its use of __has_include, which is a non-standard pre-processor extension only supported by gcc (and possibly clang).

Instead I've committed dac4945f047b65b1d887fb79d0c434e77963821d. This is slightly more work, as you need to make sure that INCLUDE_NCURSES is defined to 0 in the makefile, or however you're building it, but it achieves the same effect.

**Comment by johnsonjh** [comment]
@DavidKinder 

`__has_include` is actually a required part of the base C standard as of C23 (and has been supported for a long time before C23 in GCC since 5.x, Clang since 2016, MSVC since 19, NVC, Intel C, most embedded compilers, etc.  Widespread adoption came shortly after N2799's publication.)

But it's probably good to not require C23 features, but you can always have backwards compatibility using the preprocessor, i.e.

```c
 # undef HAS_INCLUDE
 # if defined __has_include
 #  define HAS_INCLUDE(inc) __has_include(inc)
 # else
 #  define HAS_INCLUDE(inc) 0
 # endif
```

Just in case you want to use it in the future ... you can still use the user defined macro but also HAS_INCLUDE and succeed if *either* is set.
