### ISSUE TITLE
Unix ncurses build fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by cibersheep** [DavidKinder/Level9#20]
Trying to compile on Ubuntu 20.04 ends in error:

```
$ make
cc -O2 -o level9 -I.. ../level9.c unix-curses.c -lncurses
unix-curses.c:80:10: fatal error: ncurses/curses.h: El fitxer o directori no existeix
   80 | #include <ncurses/curses.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: level9] Error 1
```

**Comment by DavidKinder** [comment]
Fixed by commit dac4945f047b65b1d887fb79d0c434e77963821d.
