### ISSUE TITLE
Can't compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by cibersheep** [DavidKinder/Level9#1]
Hi. I was trying to compile the generic code in GNU/Linux (Ubuntu 16.04 64bits) and I found some errors.
`gcc generic.c level9.h level9.c bitmap.c -o level9`
and it was compaining about:

1)
level9.c:2025:6: warning: implicit declaration of function ‘stricmp’ [-Wimplicit-function-declaration]
I changed `strincmp` for `strncmp`
also `stricmp` for `strcmp`

2)
level9.h:120:1: error: unknown type name 'FILE'
I added added: `#include <stdio.h>` at the top of level9.h

3)
/tmp/bitmap-f74ba0.o: In function `bitmap_amiga_intensity': bitmap.c:(.text+0x150a): reference to `pow' not defined
I added ` -lm` to link math library:

Finally `gcc generic.c level9.h level9.c bitmap.c -o level9` compiled the code. I can run it in the terminal (no pictures for now) but it is working apparently great.

Thanks!
